// Code generated by ent, DO NOT EDIT.

package redeemcodeclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldLTE(FieldID, id))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldRedeemCodeID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldAmount, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldClaimedAt, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldLTE(FieldAmount, v))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.FieldLTE(FieldClaimedAt, v))
}

// HasRedeemCode applies the HasEdge predicate on the "redeem_code" edge.
func HasRedeemCode() predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RedeemCodeTable, RedeemCodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedeemCodeWith applies the HasEdge predicate on the "redeem_code" edge with a given conditions (other predicates).
func HasRedeemCodeWith(preds ...predicate.RedeemCode) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(func(s *sql.Selector) {
		step := newRedeemCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemCodeClaim) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemCodeClaim) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemCodeClaim) predicate.RedeemCodeClaim {
	return predicate.RedeemCodeClaim(sql.NotPredicates(p))
}
