// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodeclaim"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RedeemCodeClaim is the model entity for the RedeemCodeClaim schema.
type RedeemCodeClaim struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RedeemCodeID holds the value of the "redeem_code_id" field.
	RedeemCodeID int64 `json:"redeem_code_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt time.Time `json:"claimed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RedeemCodeClaimQuery when eager-loading is set.
	Edges        RedeemCodeClaimEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RedeemCodeClaimEdges holds the relations/edges for other nodes in the graph.
type RedeemCodeClaimEdges struct {
	// RedeemCode holds the value of the redeem_code edge.
	RedeemCode *RedeemCode `json:"redeem_code,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RedeemCodeOrErr returns the RedeemCode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedeemCodeClaimEdges) RedeemCodeOrErr() (*RedeemCode, error) {
	if e.RedeemCode != nil {
		return e.RedeemCode, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: redeemcode.Label}
	}
	return nil, &NotLoadedError{edge: "redeem_code"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedeemCodeClaimEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RedeemCodeClaim) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case redeemcodeclaim.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case redeemcodeclaim.FieldID, redeemcodeclaim.FieldRedeemCodeID, redeemcodeclaim.FieldUserID:
			values[i] = new(sql.NullInt64)
		case redeemcodeclaim.FieldClaimedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RedeemCodeClaim fields.
func (_m *RedeemCodeClaim) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case redeemcodeclaim.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case redeemcodeclaim.FieldRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_id", values[i])
			} else if value.Valid {
				_m.RedeemCodeID = value.Int64
			}
		case redeemcodeclaim.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case redeemcodeclaim.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case redeemcodeclaim.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RedeemCodeClaim.
// This includes values selected through modifiers, order, etc.
func (_m *RedeemCodeClaim) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRedeemCode queries the "redeem_code" edge of the RedeemCodeClaim entity.
func (_m *RedeemCodeClaim) QueryRedeemCode() *RedeemCodeQuery {
	return NewRedeemCodeClaimClient(_m.config).QueryRedeemCode(_m)
}

// QueryUser queries the "user" edge of the RedeemCodeClaim entity.
func (_m *RedeemCodeClaim) QueryUser() *UserQuery {
	return NewRedeemCodeClaimClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this RedeemCodeClaim.
// Note that you need to call RedeemCodeClaim.Unwrap() before calling this method if this RedeemCodeClaim
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RedeemCodeClaim) Update() *RedeemCodeClaimUpdateOne {
	return NewRedeemCodeClaimClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RedeemCodeClaim entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RedeemCodeClaim) Unwrap() *RedeemCodeClaim {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RedeemCodeClaim is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RedeemCodeClaim) String() string {
	var builder strings.Builder
	builder.WriteString("RedeemCodeClaim(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("redeem_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedeemCodeID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("claimed_at=")
	builder.WriteString(_m.ClaimedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RedeemCodeClaims is a parsable slice of RedeemCodeClaim.
type RedeemCodeClaims []*RedeemCodeClaim
