// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodeclaim"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RedeemCodeClaimCreate is the builder for creating a RedeemCodeClaim entity.
type RedeemCodeClaimCreate struct {
	config
	mutation *RedeemCodeClaimMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *RedeemCodeClaimCreate) SetRedeemCodeID(v int64) *RedeemCodeClaimCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RedeemCodeClaimCreate) SetUserID(v int64) *RedeemCodeClaimCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RedeemCodeClaimCreate) SetAmount(v float64) *RedeemCodeClaimCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *RedeemCodeClaimCreate) SetClaimedAt(v time.Time) *RedeemCodeClaimCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *RedeemCodeClaimCreate) SetNillableClaimedAt(v *time.Time) *RedeemCodeClaimCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_c *RedeemCodeClaimCreate) SetRedeemCode(v *RedeemCode) *RedeemCodeClaimCreate {
	return _c.SetRedeemCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *RedeemCodeClaimCreate) SetUser(v *User) *RedeemCodeClaimCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the RedeemCodeClaimMutation object of the builder.
func (_c *RedeemCodeClaimCreate) Mutation() *RedeemCodeClaimMutation {
	return _c.mutation
}

// Save creates the RedeemCodeClaim in the database.
func (_c *RedeemCodeClaimCreate) Save(ctx context.Context) (*RedeemCodeClaim, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemCodeClaimCreate) SaveX(ctx context.Context) *RedeemCodeClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeClaimCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeClaimCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemCodeClaimCreate) defaults() {
	if _, ok := _c.mutation.ClaimedAt(); !ok {
		v := redeemcodeclaim.DefaultClaimedAt()
		_c.mutation.SetClaimedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemCodeClaimCreate) check() error {
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "RedeemCodeClaim.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RedeemCodeClaim.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RedeemCodeClaim.amount"`)}
	}
	if _, ok := _c.mutation.ClaimedAt(); !ok {
		return &ValidationError{Name: "claimed_at", err: errors.New(`ent: missing required field "RedeemCodeClaim.claimed_at"`)}
	}
	if len(_c.mutation.RedeemCodeIDs()) == 0 {
		return &ValidationError{Name: "redeem_code", err: errors.New(`ent: missing required edge "RedeemCodeClaim.redeem_code"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RedeemCodeClaim.user"`)}
	}
	return nil
}

func (_c *RedeemCodeClaimCreate) sqlSave(ctx context.Context) (*RedeemCodeClaim, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemCodeClaimCreate) createSpec() (*RedeemCodeClaim, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemCodeClaim{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemcodeclaim.Table, sqlgraph.NewFieldSpec(redeemcodeclaim.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(redeemcodeclaim.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(redeemcodeclaim.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = value
	}
	if nodes := _c.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.RedeemCodeTable,
			Columns: []string{redeemcodeclaim.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedeemCodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.UserTable,
			Columns: []string{redeemcodeclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeClaim.Create().
//		SetRedeemCodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeClaimUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeClaimCreate) OnConflict(opts ...sql.ConflictOption) *RedeemCodeClaimUpsertOne {
	_c.conflict = opts
	return &RedeemCodeClaimUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeClaimCreate) OnConflictColumns(columns ...string) *RedeemCodeClaimUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeClaimUpsertOne{
		create: _c,
	}
}

type (
	// RedeemCodeClaimUpsertOne is the builder for "upsert"-ing
	//  one RedeemCodeClaim node.
	RedeemCodeClaimUpsertOne struct {
		create *RedeemCodeClaimCreate
	}

	// RedeemCodeClaimUpsert is the "OnConflict" setter.
	RedeemCodeClaimUpsert struct {
		*sql.UpdateSet
	}
)

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeClaimUpsert) SetRedeemCodeID(v int64) *RedeemCodeClaimUpsert {
	u.Set(redeemcodeclaim.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsert) UpdateRedeemCodeID() *RedeemCodeClaimUpsert {
	u.SetExcluded(redeemcodeclaim.FieldRedeemCodeID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeClaimUpsert) SetUserID(v int64) *RedeemCodeClaimUpsert {
	u.Set(redeemcodeclaim.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsert) UpdateUserID() *RedeemCodeClaimUpsert {
	u.SetExcluded(redeemcodeclaim.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *RedeemCodeClaimUpsert) SetAmount(v float64) *RedeemCodeClaimUpsert {
	u.Set(redeemcodeclaim.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsert) UpdateAmount() *RedeemCodeClaimUpsert {
	u.SetExcluded(redeemcodeclaim.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RedeemCodeClaimUpsert) AddAmount(v float64) *RedeemCodeClaimUpsert {
	u.Add(redeemcodeclaim.FieldAmount, v)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *RedeemCodeClaimUpsert) SetClaimedAt(v time.Time) *RedeemCodeClaimUpsert {
	u.Set(redeemcodeclaim.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsert) UpdateClaimedAt() *RedeemCodeClaimUpsert {
	u.SetExcluded(redeemcodeclaim.FieldClaimedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemCodeClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeClaimUpsertOne) UpdateNewValues() *RedeemCodeClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeClaim.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemCodeClaimUpsertOne) Ignore() *RedeemCodeClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeClaimUpsertOne) DoNothing() *RedeemCodeClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeClaimCreate.OnConflict
// documentation for more info.
func (u *RedeemCodeClaimUpsertOne) Update(set func(*RedeemCodeClaimUpsert)) *RedeemCodeClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeClaimUpsertOne) SetRedeemCodeID(v int64) *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertOne) UpdateRedeemCodeID() *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeClaimUpsertOne) SetUserID(v int64) *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertOne) UpdateUserID() *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *RedeemCodeClaimUpsertOne) SetAmount(v float64) *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RedeemCodeClaimUpsertOne) AddAmount(v float64) *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertOne) UpdateAmount() *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateAmount()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *RedeemCodeClaimUpsertOne) SetClaimedAt(v time.Time) *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertOne) UpdateClaimedAt() *RedeemCodeClaimUpsertOne {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateClaimedAt()
	})
}

// Exec executes the query.
func (u *RedeemCodeClaimUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeClaimCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeClaimUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemCodeClaimUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemCodeClaimUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemCodeClaimCreateBulk is the builder for creating many RedeemCodeClaim entities in bulk.
type RedeemCodeClaimCreateBulk struct {
	config
	err      error
	builders []*RedeemCodeClaimCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemCodeClaim entities in the database.
func (_c *RedeemCodeClaimCreateBulk) Save(ctx context.Context) ([]*RedeemCodeClaim, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemCodeClaim, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemCodeClaimMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemCodeClaimCreateBulk) SaveX(ctx context.Context) []*RedeemCodeClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeClaimCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeClaimCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeClaim.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeClaimUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeClaimCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemCodeClaimUpsertBulk {
	_c.conflict = opts
	return &RedeemCodeClaimUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeClaimCreateBulk) OnConflictColumns(columns ...string) *RedeemCodeClaimUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeClaimUpsertBulk{
		create: _c,
	}
}

// RedeemCodeClaimUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemCodeClaim nodes.
type RedeemCodeClaimUpsertBulk struct {
	create *RedeemCodeClaimCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemCodeClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeClaimUpsertBulk) UpdateNewValues() *RedeemCodeClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeClaim.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemCodeClaimUpsertBulk) Ignore() *RedeemCodeClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeClaimUpsertBulk) DoNothing() *RedeemCodeClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeClaimCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemCodeClaimUpsertBulk) Update(set func(*RedeemCodeClaimUpsert)) *RedeemCodeClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeClaimUpsertBulk) SetRedeemCodeID(v int64) *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertBulk) UpdateRedeemCodeID() *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeClaimUpsertBulk) SetUserID(v int64) *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertBulk) UpdateUserID() *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *RedeemCodeClaimUpsertBulk) SetAmount(v float64) *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RedeemCodeClaimUpsertBulk) AddAmount(v float64) *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertBulk) UpdateAmount() *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateAmount()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *RedeemCodeClaimUpsertBulk) SetClaimedAt(v time.Time) *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *RedeemCodeClaimUpsertBulk) UpdateClaimedAt() *RedeemCodeClaimUpsertBulk {
	return u.Update(func(s *RedeemCodeClaimUpsert) {
		s.UpdateClaimedAt()
	})
}

// Exec executes the query.
func (u *RedeemCodeClaimUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemCodeClaimCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeClaimCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeClaimUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
