// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodeclaim"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RedeemCodeClaimUpdate is the builder for updating RedeemCodeClaim entities.
type RedeemCodeClaimUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemCodeClaimMutation
}

// Where appends a list predicates to the RedeemCodeClaimUpdate builder.
func (_u *RedeemCodeClaimUpdate) Where(ps ...predicate.RedeemCodeClaim) *RedeemCodeClaimUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCodeClaimUpdate) SetRedeemCodeID(v int64) *RedeemCodeClaimUpdate {
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdate) SetNillableRedeemCodeID(v *int64) *RedeemCodeClaimUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCodeClaimUpdate) SetUserID(v int64) *RedeemCodeClaimUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdate) SetNillableUserID(v *int64) *RedeemCodeClaimUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RedeemCodeClaimUpdate) SetAmount(v float64) *RedeemCodeClaimUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdate) SetNillableAmount(v *float64) *RedeemCodeClaimUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RedeemCodeClaimUpdate) AddAmount(v float64) *RedeemCodeClaimUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *RedeemCodeClaimUpdate) SetClaimedAt(v time.Time) *RedeemCodeClaimUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdate) SetNillableClaimedAt(v *time.Time) *RedeemCodeClaimUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeClaimUpdate) SetRedeemCode(v *RedeemCode) *RedeemCodeClaimUpdate {
	return _u.SetRedeemCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RedeemCodeClaimUpdate) SetUser(v *User) *RedeemCodeClaimUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RedeemCodeClaimMutation object of the builder.
func (_u *RedeemCodeClaimUpdate) Mutation() *RedeemCodeClaimMutation {
	return _u.mutation
}

// ClearRedeemCode clears the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeClaimUpdate) ClearRedeemCode() *RedeemCodeClaimUpdate {
	_u.mutation.ClearRedeemCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RedeemCodeClaimUpdate) ClearUser() *RedeemCodeClaimUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemCodeClaimUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemCodeClaimUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeClaimUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeClaimUpdate) check() error {
	if _u.mutation.RedeemCodeCleared() && len(_u.mutation.RedeemCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeClaim.redeem_code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeClaim.user"`)
	}
	return nil
}

func (_u *RedeemCodeClaimUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcodeclaim.Table, redeemcodeclaim.Columns, sqlgraph.NewFieldSpec(redeemcodeclaim.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(redeemcodeclaim.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(redeemcodeclaim.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(redeemcodeclaim.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.RedeemCodeTable,
			Columns: []string{redeemcodeclaim.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.RedeemCodeTable,
			Columns: []string{redeemcodeclaim.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.UserTable,
			Columns: []string{redeemcodeclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.UserTable,
			Columns: []string{redeemcodeclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcodeclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemCodeClaimUpdateOne is the builder for updating a single RedeemCodeClaim entity.
type RedeemCodeClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemCodeClaimMutation
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCodeClaimUpdateOne) SetRedeemCodeID(v int64) *RedeemCodeClaimUpdateOne {
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdateOne) SetNillableRedeemCodeID(v *int64) *RedeemCodeClaimUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCodeClaimUpdateOne) SetUserID(v int64) *RedeemCodeClaimUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdateOne) SetNillableUserID(v *int64) *RedeemCodeClaimUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RedeemCodeClaimUpdateOne) SetAmount(v float64) *RedeemCodeClaimUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdateOne) SetNillableAmount(v *float64) *RedeemCodeClaimUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RedeemCodeClaimUpdateOne) AddAmount(v float64) *RedeemCodeClaimUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *RedeemCodeClaimUpdateOne) SetClaimedAt(v time.Time) *RedeemCodeClaimUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *RedeemCodeClaimUpdateOne) SetNillableClaimedAt(v *time.Time) *RedeemCodeClaimUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeClaimUpdateOne) SetRedeemCode(v *RedeemCode) *RedeemCodeClaimUpdateOne {
	return _u.SetRedeemCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RedeemCodeClaimUpdateOne) SetUser(v *User) *RedeemCodeClaimUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RedeemCodeClaimMutation object of the builder.
func (_u *RedeemCodeClaimUpdateOne) Mutation() *RedeemCodeClaimMutation {
	return _u.mutation
}

// ClearRedeemCode clears the "redeem_code" edge to the RedeemCode entity.
func (_u *RedeemCodeClaimUpdateOne) ClearRedeemCode() *RedeemCodeClaimUpdateOne {
	_u.mutation.ClearRedeemCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RedeemCodeClaimUpdateOne) ClearUser() *RedeemCodeClaimUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the RedeemCodeClaimUpdate builder.
func (_u *RedeemCodeClaimUpdateOne) Where(ps ...predicate.RedeemCodeClaim) *RedeemCodeClaimUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemCodeClaimUpdateOne) Select(field string, fields ...string) *RedeemCodeClaimUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemCodeClaim entity.
func (_u *RedeemCodeClaimUpdateOne) Save(ctx context.Context) (*RedeemCodeClaim, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCodeClaimUpdateOne) SaveX(ctx context.Context) *RedeemCodeClaim {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemCodeClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCodeClaimUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCodeClaimUpdateOne) check() error {
	if _u.mutation.RedeemCodeCleared() && len(_u.mutation.RedeemCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeClaim.redeem_code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RedeemCodeClaim.user"`)
	}
	return nil
}

func (_u *RedeemCodeClaimUpdateOne) sqlSave(ctx context.Context) (_node *RedeemCodeClaim, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcodeclaim.Table, redeemcodeclaim.Columns, sqlgraph.NewFieldSpec(redeemcodeclaim.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemCodeClaim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemcodeclaim.FieldID)
		for _, f := range fields {
			if !redeemcodeclaim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemcodeclaim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(redeemcodeclaim.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(redeemcodeclaim.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(redeemcodeclaim.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.RedeemCodeTable,
			Columns: []string{redeemcodeclaim.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.RedeemCodeTable,
			Columns: []string{redeemcodeclaim.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.UserTable,
			Columns: []string{redeemcodeclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeclaim.UserTable,
			Columns: []string{redeemcodeclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RedeemCodeClaim{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcodeclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
